/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package molediggers;
import javax.swing.*; 
import java.awt.*; 
import java.util.List; 
import javax.swing.text.*; 
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
JTextPane leaderboardArea; 
 private void appendToLeaderboard(String text) { 
        try { 
            leaderboardArea.getDocument().insertString( 
                    leaderboardArea.getDocument().getLength(), 
                    text, 
                    null); 
        } catch (Exception e) { 
            e.printStackTrace(); 
        } 
    } 
    public Menu() { 
        setTitle("MoleDiggers Menu"); 
        setSize(400, 500); 
        setDefaultCloseOperation(EXIT_ON_CLOSE); 
        setLayout(new BorderLayout()); 
 
        JLabel title = new JLabel("MOLE DIGGERS", SwingConstants.CENTER); 
        title.setFont(new Font("Arial", Font.BOLD, 34)); 
        title.setForeground(new Color(214, 174, 96)); 
 
        JButton playBtn = new JButton("LOBBY"); 
        JButton refreshBtn = new JButton("REFRESH LEADERBOARD"); 
 
        playBtn.setFont(new Font("Arial", Font.BOLD, 16)); 
        playBtn.setBackground(new Color(214, 174, 96)); 
        playBtn.setForeground(Color.BLACK); 
        playBtn.setFocusPainted(false); 
        playBtn.setBorderPainted(false); 
 
        refreshBtn.setFont(new Font("Arial", Font.BOLD, 14)); 
        refreshBtn.setBackground(new Color(120, 90, 60)); 
        refreshBtn.setForeground(Color.WHITE); 
        refreshBtn.setFocusPainted(false); 
        refreshBtn.setBorderPainted(false); 
 
        leaderboardArea = new JTextPane(); 
        leaderboardArea.setEditable(false); 
 
        leaderboardArea.setFont(new Font("Monospaced", Font.PLAIN, 18)); 
        leaderboardArea.setBackground(new Color(30, 25, 20)); 
        leaderboardArea.setForeground(new Color(255, 255, 255)); 
 
        StyledDocument doc = leaderboardArea.getStyledDocument(); 
        SimpleAttributeSet center = new SimpleAttributeSet(); 
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER); 
        doc.setParagraphAttributes(0, doc.getLength(), center, false); 
 
        add(title, BorderLayout.NORTH); 
        add(new JScrollPane(leaderboardArea), BorderLayout.CENTER); 
 
        JPanel bottom = new JPanel(); 
        bottom.add(playBtn); 
        bottom.add(refreshBtn); 
 
        getContentPane().setBackground(new Color(46, 35, 28)); 
        bottom.setBackground(new Color(60, 45, 35)); 
 
        add(bottom, BorderLayout.SOUTH); 
 
        // BUTTON ACTIONS 
        playBtn.addActionListener(e -> { 
                new Bglob().setVisible(true); 
                dispose(); 
        });
 
        refreshBtn.addActionListener(e -> loadLeaderboard()); 
 
        loadLeaderboard(); 
 
        setLocationRelativeTo(null); 
    } 
 
    private void loadLeaderboard() { 
        List<String> scores = Leaderboard.getTopScores(); 
 
        leaderboardArea.setText(""); 
 
        appendToLeaderboard("LEADERBOARD\n\n"); 
        appendToLeaderboard("RANK      NAME     SCORE\n"); 
        appendToLeaderboard("-----------------------\n"); 
 
        int rank = 1; 
        for (String s : scores) { 
            String[] parts = s.split(","); 
 
            appendToLeaderboard( 
                    String.format("%-6d %-8s %5s\n", 
                            rank, parts[0], parts[1])); 
 
            rank++; 
        } 
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
